# Generated by Django 4.1.7 on 2023-05-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_cycle", models.DateField()),
                ("end_cycle", models.DateField()),
                ("price_cycle", models.FloatField(max_length=12)),
                ("days_of_cycle", models.IntegerField(max_length=10)),
            ],
        ),
    ]
